
# Sentiment Analysis

## Objective:
In this module, we aim to explore the different regression and classification models and try to analyse which model performs best on a given data.

- **1. Text Data Cleaning and Preprocessing:**
     - Remove noise such as punctuation, stopwords, and special characters.
     - Apply tokenization, stemming, and lemmatization to standardize text data.
     - Prepare the text data for further analysis and modeling.

- **2. Text Vectorization Techniques:**
     - Utilize techniques such as CountVectorizer, TF-IDF, or Doc2Vec to vectorize the cleaned text data.

- **3. Naive Bayes, KNN Models Implementation:**
    - Apply the Naive Bayes & KNN algorithms to classify text data based on the vectorized inputs.
     - Evaluate the model's performance using metrics such as accuracy, precision, recall, and F1-score.

- **4. Hyperparameter Tuning :**
     - Perform hyperparameter tuning using techniques such as GridSearchCV or RandomizedSearchCV.
     - Identify the optimal set of hyperparameters that maximize the model's performance.


##1. Introduction

Sentiment analysis, often referred to as opinion mining, is a natural language processing (NLP) technique used to determine the emotional tone behind a body of text. It involves classifying text into categories like positive, negative, or neutral, thereby offering valuable insights into public opinion, customer feedback, and brand perception.

<center><img src="https://media.sproutsocial.com/uploads/2023/07/Sentiment-analysis-HUB-Final.jpg" width = 500 height = 300 /></center>

The process is crucial in various applications, such as understanding customer sentiments in reviews, monitoring social media for brand sentiment, and gauging public opinion on specific topics.

##2. Steps involved

This notebook leverages algorithms and machine learning models to transform unstructured text data into structured information, enabling the classification of text into `Positive`, `Negative`, and `Neutral` categories.

1. **Data Collection** <br>
  a. **Gather Text Data:** The data is downloded from kaggle please refer to this <a href='https://www.kaggle.com/datasets/kashishparmar02/social-media-sentiments-analysis-dataset'>link</a> for more details about the data.

  b. **Labeling Data:** Label the text data with corresponding sentiment categories such as `Positive`, `Negative`, and `Neutral`.
2. **Data Preprocessing** <br>
  a. **Text Cleaning:** Remove noise from the text, such as processing hashtags, special characters, and stopwords (e.g., "the," "and").

  b. **Tokenization:** Break down the text into individual words or tokens.

  c. **Lemmatization/Stemming:** Reduce words to their base or root form (e.g., "running" to "run").

3. **Feature Engineering**<br>
  a. **Vectorization:** Convert text data into numerical features using methods like Bag of Words (BoW), TF-IDF, or word embeddings (e.g., Word2Vec, Doc2Vec, GloVe, spacy). In this notebook, we will generate word embeddings using `Doc2Vec`.

4. **Model Selection**<br>
  a. **Choose an Algorithm:** Select a machine learning algorithm suitable for classification tasks. Common choices include Logistic Regression, Support Vector Machines (SVM), Naive Bayes, and deep learning models like RNNs or Transformers. In this notebook we will use `Naive Bayes`, `Logistic regression` and `K-Nearest Neighbors (KNN)` for classification.

  b. **Hyperparameter tunning and Model Training:** Train the selected model using the labeled data and tune hyper parameters to it's optimal performance.

5. **Model Evaluation**<br>
  a. **Performance Metrics:** Use metrics like accuracy, precision, recall, F1-score, and Confusion matrix to assess the model's effectiveness.
  We are evaluating the performance of two classification models: `Naive Bayes`, and `K-Nearest Neighbors (KNN)`. Each model is trained using different word embeddings:

  b. **Doc2Vec Embeddings:** These embeddings are generated from a model specifically trained on our sentiment analysis dataset.

Based on the observations above, we aim to draw final conclusions regarding the comparative performance of the models with different word embeddings.

In [4]:
# Import the necessary libraries
# Data manipulation and numerical operations
import pandas as pd
import numpy as np

# Data visualization
import seaborn as sns  # For creating attractive and informative statistical graphics
import matplotlib.pyplot as plt  # For plotting graphs and charts

# Utility for text processing
import re

# Import the warnings module, which allows control over warning messages
import warnings

# Suppress all warnings in the script
warnings.filterwarnings("ignore")

Matplotlib is building the font cache; this may take a moment.

In [6]:
# Machine learning models and metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (accuracy_score, classification_report,
                             precision_score, recall_score, f1_score,
                             confusion_matrix)

In [12]:
import sys
print(sys.executable)

/Users/nishantsnaik/Documents/interview-kickstart/JupyterProject/.venv/bin/python

In [14]:
# Importing Natural Language Processing (NLP) libraries
import spacy
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

# Load spaCy's English language model
nlp = spacy.load("en_core_web_sm")

# Download VADER lexicon if not already downloaded
nltk.download('vader_lexicon')

# Initialize VADER sentiment intensity analyzer
sid = SentimentIntensityAnalyzer()

# Initialize the PorterStemmer
stemmer = PorterStemmer()

# Download NLTK stopwords if not already downloaded
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/nishantsnaik/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# 2. Steps involved

# 2.1 Data Collection

## 2.1.1 Gather text data<br>
 The data is downloded from kaggle <a href='https://www.kaggle.com/datasets/kashishparmar02/social-media-sentiments-analysis-dataset'>link</a>

 The dataset `Social Media Sentiments Analysis` captures a vibrant tapestry of emotions, trends, and interactions across various social media platforms. This dataset provides a snapshot of user-generated content, encompassing text, timestamps, hashtags, countries, likes, and retweets. Each entry unveils unique stories—moments of surprise, excitement, admiration, thrill, contentment, and more—shared by individuals worldwide.

In [16]:
#Load data from the csv file
sentiment_data = pd.read_csv('sentimentdataset.csv')

In [17]:
# Display the first few rows of the sentiment dataset to get an overview
sentiment_data.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [18]:
# Drop the unwanted columns
sentiment_data.drop(columns=['Unnamed: 0.1','Unnamed: 0'],inplace=True)
sentiment_data.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [19]:
# Display a concise summary of the sentiment dataset
sentiment_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Text       732 non-null    str
 1   Sentiment  732 non-null    str
 2   Timestamp  732 non-null    str
 3   User       732 non-null    str
 4   Platform   732 non-null    str
 5   Hashtags   732 non-null    str
 6   Retweets   732 non-null    float64
 7   Likes      732 non-null    float64
 8   Country    732 non-null    str
 9   Year       732 non-null    int64
 10  Month      732 non-null    int64
 11  Day        732 non-null    int64
 12  Hour       732 non-null    int64
dtypes: float64(2), int64(4), str(7)
memory usage: 74.5 KB

##Observation

There are no null values in the data.

Also, the columns `Text`, `Sentiment`, `Platform`, and `Hashtags` appear to be essential for our sentiment analysis. The `Text` and `Hashtags` columns will help us identify the sentiment expressed in the text, while the `Sentiment` column will serve as the label for our analysis. Additionally, the `Platform` column will provide information on the source from which the text was extracted.

In [20]:
useful_columns = ['Text', 'Sentiment', 'Platform', 'Hashtags']

In [21]:
# Filter the sentiment dataset to include only the relevant columns
sentiment_data = sentiment_data[useful_columns]

In [22]:
# Display the first few rows of the sentiment dataset to get an overview
sentiment_data.head()

,Text,Sentiment,Platform,Hashtags
0,Enjoying a beautiful day at the park! ...,Positive,Twitter,#Nature #Park
1,Traffic was terrible this morning. ...,Negative,Twitter,#Traffic #Morning
2,Just finished an amazing workout! 💪 ...,Positive,Instagram,#Fitness #Workout
3,Excited about the upcoming weekend getaway! ...,Positive,Facebook,#Travel #Adventure
4,Trying out a new recipe for dinner tonight. ...,Neutral,Instagram,#Cooking #Food